### ISSUE TITLE
Problem with wide angel cameras

### ISSUE THREAD

**Issue by bekatom** [DoubangoTelecom/ultimateMRZ-SDK#41] opened 2020-10-05 11:55 UTC
Has anyone had a similar type of problem when a photo is taken with a wide-angle camera it doesn't works. 
I checked the same photo on https://www.doubango.org/webapps/mrz/ but the same 
``` No MRZ zone found on the image. ```

Photo quality is good and the MRZ area is very well presented
Calling from API it returns just two key and nothing else 

``` {"duration":41, "frame_id":2} ```

We checked with this models all have wide angel cameras and have the same problem. 

SM-G975F
SM-G975F
SM-G975U1
SM-A715F
SM-A515F

Thanks!

**Comment by DoubangoTelecom** [comment] 2020-10-05 18:56
Duplicate of #42

**Closed by DoubangoTelecom** 2020-10-05 18:56 UTC
